import type { ReportWithCompetitor } from "@/lib/agent/types";
import { getAppBaseUrl } from "@/lib/env";

/** Extra body beyond summary when the stored narrative is clearly longer. */
const FULL_REPORT_SNIPPET_CHARS = 1200;

/** Skip excerpt when fullReport is only slightly longer than summary (likely redundant). */
const SUMMARY_LENGTH_MARGIN = 80;

function truncatePlainText(text: string, maxChars: number): string {
  const t = text.trim().replace(/\s+/g, " ");
  if (t.length <= maxChars) {
    return t;
  }
  return `${t.slice(0, maxChars - 1)}…`;
}

export function formatSlackMessage(reports: ReportWithCompetitor[]) {
  if (!reports.length) {
    return "No competitor reports were generated.";
  }

  const baseUrl = getAppBaseUrl();

  const lines = reports.map((report) => {
    const competitorName = report.competitor?.name ?? "Unknown competitor";
    const blocks: string[] = [];

    blocks.push(`*${competitorName}*`);
    blocks.push(`_${report.title}_`);
    blocks.push(report.summary);

    const full = report.fullReport.trim();
    const summary = report.summary.trim();
    if (full.length > summary.length + SUMMARY_LENGTH_MARGIN) {
      blocks.push("");
      blocks.push("*More detail* _(truncated — open dashboard for full markdown)_");
      blocks.push(truncatePlainText(full, FULL_REPORT_SNIPPET_CHARS));
    }

    if (baseUrl) {
      const url = `${baseUrl}/reports/${report.id}`;
      blocks.push("");
      blocks.push(`<${url}|Open full report in dashboard>`);
    }

    return blocks.join("\n");
  });

  return `
:chart_with_upwards_trend: *Daily Competitor Analysis Report*

${lines.join("\n\n")}

Generated by the Competitor Analysis Agent.
`.trim();
}
