import type { ReportWithCompetitor } from "@/lib/agent/types";
import { getAppBaseUrl } from "@/lib/env";

/** How many characters of fullReport we paste into Slack when it is much longer than the summary. */
const PREVIEW_MAX_CHARS = 1200;

/** If fullReport is only a bit longer than the summary, the preview would repeat the same idea — skip it. */
const SUMMARY_LENGTH_MARGIN = 80;

/**
 * Turn stored markdown into something Slack understands a bit better:
 * - # headings become a bold Slack line (no hash characters)
 * - **word** becomes *word* (Slack bold)
 * - [text](url) becomes Slack's <url|text> link
 * Line breaks are kept; we only squeeze runs of blank lines.
 */
function slackFriendlyExcerpt(raw: string): string {
  const normalized = raw.replace(/\r\n/g, "\n");

  const lines = normalized.split("\n").map((line) => {
    const heading = line.match(/^(\s*)(#{1,6})\s+(.+)$/);
    if (heading) {
      const indent = heading[1];
      const title = heading[3].trim();
      return `${indent}*${title}*`;
    }
    return line;
  });

  let out = lines.join("\n");

  out = out.replace(/\*\*([^*]+)\*\*/g, "*$1*");
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "<$2|$1>");
  out = out.replace(/\n{3,}/g, "\n\n");

  return out.trim();
}

/** Shorten text for Slack, but keep newlines. Prefer cutting at a line or word boundary. */
function trimForSlack(text: string, maxChars: number): string {
  if (text.length <= maxChars) {
    return text;
  }

  const slice = text.slice(0, maxChars - 1);
  const lastNewline = slice.lastIndexOf("\n");
  const lastSpace = slice.lastIndexOf(" ");
  const breakAt =
    lastNewline > maxChars * 0.7
      ? lastNewline
      : lastSpace > maxChars * 0.85
        ? lastSpace
        : maxChars - 1;

  const cut = breakAt > 0 ? slice.slice(0, breakAt) : slice;
  return `${cut.trimEnd()}…`;
}

export function formatSlackMessage(reports: ReportWithCompetitor[]) {
  if (!reports.length) {
    return "No competitor reports were generated.";
  }

  const baseUrl = getAppBaseUrl();

  const sections = reports.map((report) => {
    const name = report.competitor?.name ?? "Unknown competitor";
    const pieces: string[] = [];

    pieces.push(`*${name}*`);
    pieces.push(`_${report.title}_`);
    pieces.push(report.summary.trim());

    const full = report.fullReport.trim();
    const short = report.summary.trim();
    const showPreview =
      full.length > short.length + SUMMARY_LENGTH_MARGIN;

    if (baseUrl) {
      const url = `${baseUrl}/reports/${report.id}`;
      pieces.push("");
      pieces.push(`<${url}|Open full report in dashboard>`);
    }

    if (showPreview) {
      pieces.push("");
      const previewNote = baseUrl
        ? "*Extra detail below* _(trimmed; use the link above for the full write-up)_"
        : "*Extra detail below* _(trimmed)_";
      pieces.push(previewNote);
      pieces.push(trimForSlack(slackFriendlyExcerpt(full), PREVIEW_MAX_CHARS));
    }

    return pieces.join("\n");
  });

  return `
:chart_with_upwards_trend: *Daily Competitor Analysis Report*

${sections.join("\n\n")}

Generated by the Competitor Analysis Agent.
`.trim();
}
